AR = ['C:\\msys64\\mingw64\\bin\\ar.exe']
ARFLAGS = ['rcs']
BINDIR = 'C:\\Users\\38063\\AppData\\Local\\Temp/bin'
CC = '/c/msys64/mingw64/bin/g++'
CC_VERSION = ('12', '2', '0')
CPPPATH_ST = '-I%s'
CXX = ['C:\\msys64\\mingw64\\bin\\g++.exe']
CXXFLAGS = ['-Wall', '-lmysql']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = []
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DEFINES_ST = '-D%s'
DEST_BINFMT = 'pe'
DEST_CPU = 'x86_64'
DEST_OS = 'win32'
G__ = ['C:\\msys64\\mingw64\\bin\\g++.exe']
IMPLIBDIR = 'C:\\Users\\38063\\AppData\\Local\\Temp/lib'
IMPLIB_ST = '-Wl,--out-implib,%s'
INCLUDES = ['C:/Program Files/MySQL/MySQL Server 8.0/include']
LIB = ['mysql']
LIBDIR = 'C:\\Users\\38063\\AppData\\Local\\Temp/bin'
LIBPATH = ['C:/Program Files/MySQL/MySQL Server 8.0/lib', '../dll', './bin']
LIBPATH_ST = '-L%s'
LIB_MYSQL = ['mysqlclient']
LIB_ST = '-l%s'
LINKFLAGS = ['-Wl,--enable-auto-import']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CXX = ['C:\\msys64\\mingw64\\bin\\g++.exe']
OUT = 'build_output'
PREFIX = 'C:\\Users\\38063\\AppData\\Local\\Temp'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
cxxprogram_PATTERN = '%s.exe'
cxxshlib_PATTERN = '%s.dll'
cxxstlib_PATTERN = 'lib%s.a'
implib_PATTERN = '%s.dll.a'
macbundle_PATTERN = '%s.bundle'
